name: Deployment - Network

on:
    push:
        branches:
            - main
        paths: 
            - "parameters/resource-groups.connectivity.bicepparam"
            - "parameters/virtual-wan.connectivity.bicepparam"
    pull_request:
        branches:
            - main
        paths:
            - "parameters/resource-groups.connectivity.bicepparam"
            - "parameters/virtual-wan.connectivity.bicepparam"
    workflow_dispatch:

permissions:
    id-token: write
    contents: write
    pull-requests: write

env:
    ENV_FILE: ".env"
    IS_PULL_REQUEST: "${{ github.event_name == 'pull_request' }}"

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: "Remove Quotation Marks from Environment File"
              uses: azure/powershell@v1
              with:
                inlineScript: |
                    Write-Host $ENV_FILE
                    (Get-Content -Path $env:ENV_FILE -Encoding UTF8) | ForEach-Object {$_ -replace '"',''} | Out-File -FilePath $env:ENV_FILE -Encoding UTF8
                azPSVersion: "latest"

            - name: Import Environment Variables from File
              run: cat ${{ env.ENV_FILE }} >> $GITHUB_ENV
            
            - name: OIDC Login
              uses: azure/login@v1
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ env.CONNECTIVITY_SUBSCRIPTION_ID }}
                  enable-AzPSSession: true

            - name: "Resource Groups Deployment"
              uses: azure/powershell@v1
              with:
                inlineScript: |
                    .\src\scripts\Deploy-ALZSubscriptionScope.ps1 -Name alz-ConnectivityRGDeploy -TemplateParameterFile 'parameters/resource-groups.connectivity.bicepparam'
                azPSVersion: "latest"

            - name: "Virtual WAN Deployment"
              uses: azure/powershell@v1
              with:
                inlineScript: |
                    .\src\scripts\Deploy-ALZResourceGroupScope.ps1 -Name alz-ConnectivityVWanDeploy -ResourceGroupName ${{ env.CONNECTIVITY_RESOURCE_GROUP }} -TemplateParameterFile 'parameters/virtual-wan.connectivity.bicepparam'
                azPSVersion: "latest"